import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from 'sonner'
const vazirFont = localFont({
  src: "./fonts/Vazirmatn[wght].woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vazirFont.className} antialiased`}>
      <Toaster richColors />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
